package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
	"syscall"

	"golang.org/x/term"

	"hidemyenv/internal/doctor"
	"hidemyenv/internal/dotenv"
	"hidemyenv/internal/keychain"
	"hidemyenv/internal/runner"
	"hidemyenv/internal/vault"
)

const (
	configPath  = ".hidemyenv.toml"
	examplePath = ".env.example"
	safePath    = ".env.safe"
)

var stdinReader = bufio.NewReader(os.Stdin)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "hidemyenv:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 0 {
		usage()
		return nil
	}
	switch args[0] {
	case "init":
		return initProject()
	case "set":
		return setSecret(args[1:])
	case "list":
		return listSecrets()
	case "get":
		return getSecret(args[1:])
	case "safe":
		return writeSafeFile()
	case "run":
		return runCommand(args[1:])
	case "doctor":
		return runDoctor()
	case "keychain":
		return keychainCommand(args[1:])
	case "help", "--help", "-h":
		usage()
		return nil
	default:
		return fmt.Errorf("unknown command: %s", args[0])
	}
}

func usage() {
	fmt.Println(`hidemyenv keeps local secrets out of AI-readable plaintext files.

Usage:
  hidemyenv init
  hidemyenv set KEY
  hidemyenv list
  hidemyenv get KEY
  hidemyenv safe
  hidemyenv run -- <command>
  hidemyenv doctor
  hidemyenv keychain status|store|delete`)
}

func initProject() error {
	if err := writeFileIfMissing(configPath, []byte(defaultConfig())); err != nil {
		return err
	}
	if err := writeFileIfMissing(examplePath, []byte("# Add non-secret defaults here. Secret values live in .env.hidemyenv.\n")); err != nil {
		return err
	}
	if err := writeFileIfMissing(safePath, []byte("# Redacted env file generated by hidemyenv.\n")); err != nil {
		return err
	}
	if err := writeFileIfMissing(vault.DefaultPath, mustJSONVault()); err != nil {
		return err
	}
	if err := ensureGitignore(); err != nil {
		return err
	}
	fmt.Println("initialized hidemyenv")
	return nil
}

func setSecret(args []string) error {
	if len(args) != 1 || strings.TrimSpace(args[0]) == "" {
		return errors.New("usage: hidemyenv set KEY")
	}
	name := strings.TrimSpace(args[0])
	if !vault.ValidKey(name) {
		return fmt.Errorf("invalid env key: %s", name)
	}
	value, err := readHidden("Secret value: ")
	if err != nil {
		return err
	}
	password, err := readVaultPassword()
	if err != nil {
		return err
	}
	f, err := vault.Load(vault.DefaultPath)
	if err != nil {
		return err
	}
	if err := f.Set(name, value, password); err != nil {
		return err
	}
	if err := f.Save(vault.DefaultPath); err != nil {
		return err
	}
	return writeSafeFile()
}

func listSecrets() error {
	f, err := vault.Load(vault.DefaultPath)
	if err != nil {
		return err
	}
	for _, key := range f.Keys() {
		fmt.Println(key)
	}
	return nil
}

func getSecret(args []string) error {
	if len(args) != 1 || !vault.ValidKey(args[0]) {
		return errors.New("usage: hidemyenv get KEY")
	}
	f, err := vault.Load(vault.DefaultPath)
	if err != nil {
		return err
	}
	for _, key := range f.Keys() {
		if key == args[0] {
			fmt.Printf("%s=%s\n", key, dotenv.RedactedValue)
			return nil
		}
	}
	return fmt.Errorf("secret not found: %s", args[0])
}

func writeSafeFile() error {
	f, err := vault.Load(vault.DefaultPath)
	if err != nil {
		return err
	}
	content, err := dotenv.GenerateSafe(examplePath, f.Keys())
	if err != nil {
		return err
	}
	if err := os.WriteFile(safePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write safe env: %w", err)
	}
	fmt.Println("wrote .env.safe")
	return nil
}

func runCommand(args []string) error {
	if len(args) > 0 && args[0] == "--" {
		args = args[1:]
	}
	password, err := readVaultPassword()
	if err != nil {
		return err
	}
	f, err := vault.Load(vault.DefaultPath)
	if err != nil {
		return err
	}
	values, err := f.Values(password)
	if err != nil {
		return err
	}
	return runner.Run(args, values)
}

func runDoctor() error {
	wd, err := os.Getwd()
	if err != nil {
		return err
	}
	findings := doctor.Check(wd)
	if len(findings) == 0 {
		fmt.Println("no issues found")
		return nil
	}
	for _, finding := range findings {
		fmt.Printf("%s: %s\n", finding.Severity, finding.Message)
	}
	return fmt.Errorf("doctor found %d issue(s)", len(findings))
}

func keychainCommand(args []string) error {
	if len(args) != 1 {
		return errors.New("usage: hidemyenv keychain status|store|delete")
	}
	account, err := projectKeychainAccount()
	if err != nil {
		return err
	}
	switch args[0] {
	case "status":
		if !keychain.Available() {
			fmt.Println("keychain unavailable")
			return nil
		}
		_, ok, err := keychain.Get(account)
		if err != nil {
			return err
		}
		if ok {
			fmt.Println("keychain password stored for this project")
		} else {
			fmt.Println("no keychain password stored for this project")
		}
		return nil
	case "store":
		if !keychain.Available() {
			return errors.New("keychain unavailable")
		}
		password, err := readPasswordPrompt()
		if err != nil {
			return err
		}
		if err := keychain.Store(account, password); err != nil {
			return err
		}
		fmt.Println("stored vault password in keychain for this project")
		return nil
	case "delete":
		if !keychain.Available() {
			return errors.New("keychain unavailable")
		}
		deleted, err := keychain.Delete(account)
		if err != nil {
			return err
		}
		if deleted {
			fmt.Println("deleted keychain password for this project")
		} else {
			fmt.Println("no keychain password stored for this project")
		}
		return nil
	default:
		return errors.New("usage: hidemyenv keychain status|store|delete")
	}
}

func readVaultPassword() (string, error) {
	account, err := projectKeychainAccount()
	if err == nil && keychain.Available() {
		password, ok, err := keychain.Get(account)
		if err != nil {
			return "", err
		}
		if ok {
			return password, nil
		}
	}
	return readPasswordPrompt()
}

func readPasswordPrompt() (string, error) {
	return readHidden("Vault password: ")
}

func projectKeychainAccount() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return keychain.ProjectAccount(wd)
}

func readHidden(prompt string) (string, error) {
	if term.IsTerminal(int(syscall.Stdin)) {
		fmt.Fprint(os.Stderr, prompt)
		data, err := term.ReadPassword(int(syscall.Stdin))
		fmt.Fprintln(os.Stderr)
		if err != nil {
			return "", fmt.Errorf("read input: %w", err)
		}
		return string(data), nil
	}
	value, err := stdinReader.ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return "", fmt.Errorf("read input: %w", err)
	}
	return strings.TrimRight(value, "\r\n"), nil
}

func writeFileIfMissing(path string, data []byte) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.WriteFile(path, data, 0600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func ensureGitignore() error {
	patterns := []string{".env", ".env.*", "!.env.example", "!.env.safe", ".env.decrypted", ".env.plain"}
	path := ".gitignore"
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return os.WriteFile(path, []byte(strings.Join(patterns, "\n")+"\n"), 0644)
	}
	if err != nil {
		return fmt.Errorf("read .gitignore: %w", err)
	}
	content := string(data)
	missing := make([]string, 0)
	for _, pattern := range patterns {
		if !containsLine(content, pattern) {
			missing = append(missing, pattern)
		}
	}
	if len(missing) == 0 {
		return nil
	}
	sort.Strings(missing)
	if len(content) > 0 && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += strings.Join(missing, "\n") + "\n"
	return os.WriteFile(path, []byte(content), 0644)
}

func containsLine(content, want string) bool {
	for _, line := range strings.Split(content, "\n") {
		if strings.TrimSpace(line) == want {
			return true
		}
	}
	return false
}

func defaultConfig() string {
	return `version = 1
encrypted_file = ".env.hidemyenv"
example_file = ".env.example"
safe_file = ".env.safe"

[policy]
ai_safe = true
allow_plaintext_export = false
allow_secret_print = false
require_human_unlock = true
`
}

func mustJSONVault() []byte {
	f := vault.New()
	data, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		panic(err)
	}
	data = append(data, '\n')
	return data
}
